['intro',false] call BIS_fnc_blackOut;
COMMON_DONE = false ;
player loadStatus "playerstate";
[] execVM 'functions\dynamicSimulationRunner.sqf';
[] execVM 'common.sqf';
[] execVM 'briefing.sqf';
waitUntil {COMMON_DONE};
// private _groupsNamed = false;
_groupsNamed = [] execVM 'nameAllGroups.sqf';
// TCL_Initialize = True; 
// TCL_Path = "TCL_System\";
// call compile preprocessFileLineNumbers (TCL_Path+"TCL_Preprocess.sqf");
// [300, false, 6] execFSM 'DCO_Fsm.fsm';
parsingNamespace setVariable ['VCM_ARTYENABLE', false];
ACTIVE_TRIGGER = []execVM 'functions\findAndActivateNearestTrigger.sqf';
[] spawn jMD_fnc_spawnLoop;
sleep 5;
['intro', true] call BIS_fnc_blackIn;